apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: torrelay3
  name: torrelay3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: torrelay3
    spec:
      containers:
      - env:
        - name: RELAY_NICKNAME
          value: torrelay3
        image: nishedcob/tor-relay:test
        name: torrelay3
        resources: {}
      restartPolicy: Always
status: {}
